package wsslergsw

import (
	"math"
	"math/rand"
	"testing"

	"github.com/tuneinsight/lattigo/v6/core/rgsw"
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
)

func TestRegister(t *testing.T) {
	params := SetupParams(8)
	sk, evk := SetupKeys(params)

	enc := rgsw.NewEncryptor(params.RLWE, sk)
	dec := rlwe.NewDecryptor(params.RLWE, sk)
	eval := rgsw.NewEvaluator(params.RLWE, evk)

	p := Party{Weight: 3, Commitment: 12} // 4-bit commitment, see TestAggregate
	reg := Register(enc, params, p)

	assertOneHot(t, "ctW", decryptRGSW(enc, dec, eval, params, reg.CtW), params.Stride*int(p.Weight), 1)

	wantH := make([]float64, params.RLWE.N())
	for k := uint64(0); k < p.Weight; k++ {
		wantH[params.Stride*int(k)] = float64(p.Commitment)
	}
	assertVec(t, "ctH", DecodeCoeffs(params.RLWE, dec.DecryptNew(reg.CtH), params.Delta), wantH)

	nonzero, val := findNonzero(t, decryptRGSW(enc, dec, eval, params, reg.CtR))
	if math.Abs(val-1) > 1e-6 {
		t.Errorf("ctR: coeff[%d] = %v, want 1", nonzero, val)
	}
	if nonzero%params.Stride != 0 {
		t.Errorf("ctR: nonzero coeff at %d not aligned to stride %d", nonzero, params.Stride)
	}
	if nonzero/params.Stride >= int(params.TotalWt) {
		t.Errorf("ctR: sampled r=%d out of range [0, totalWeight)", nonzero/params.Stride)
	}
}

// TestAggregate builds registrations for the same 5-party/weight-8 scenario
// as the HIENAA reference test, and checks [Aggregate]'s two-pass external
// product fold against an independent plain-Go mirror of the same
// computation ([refCombineEcd]/[refAggregate]).
func TestAggregate(t *testing.T) {
	parties := []Party{
		{Weight: 1, Commitment: 9},
		{Weight: 2, Commitment: 10},
		{Weight: 1, Commitment: 11},
		{Weight: 3, Commitment: 12},
		{Weight: 1, Commitment: 13},
	}

	params := SetupParams(8)
	sk, evk := SetupKeys(params)

	enc := rgsw.NewEncryptor(params.RLWE, sk)
	dec := rlwe.NewDecryptor(params.RLWE, sk)
	eval := rgsw.NewEvaluator(params.RLWE, evk)

	regs, leaves := registerAll(t, enc, dec, eval, params, parties)

	agg := Aggregate(eval, Identity(enc.Encryptor, params), regs)
	want := refAggregate(params.RLWE.N(), params.Stride, leaves)

	assertVec(t, "agg", DecodeCoeffs(params.RLWE, dec.DecryptNew(agg), params.Delta), want.h)
}

// TestTrace checks the relative trace over the subring generated by
// Y = X^Stride in isolation: a message living in that subring should have its
// constant term scaled by W and every other subring coefficient annihilated.
// The message is random and densely populated (rather than a single one-hot
// coefficient) so that the test also catches the other W-1 slots leaking into
// slot 0, or failing to cancel fully.
func TestTrace(t *testing.T) {
	const totalWeight = 8

	params := SetupParams(totalWeight)
	sk, evk := SetupKeys(params)

	enc := rlwe.NewEncryptor(params.RLWE, sk)
	dec := rlwe.NewDecryptor(params.RLWE, sk)
	eval := rlwe.NewEvaluator(params.RLWE, evk)

	coeffs := make([]uint64, params.RLWE.N())
	vals := make([]uint64, totalWeight)
	for j := range vals {
		vals[j] = uint64(rand.Intn(16)) // 4-bit, as in TestAggregate
		coeffs[params.Stride*j] = vals[j]
	}

	ct, err := enc.EncryptNew(EncodeCoeffs(params.RLWE, coeffs, params.Delta))
	if err != nil {
		t.Fatal(err)
	}

	traced, err := Trace(eval, ct, 2*totalWeight)
	if err != nil {
		t.Fatal(err)
	}

	want := make([]float64, params.RLWE.N())
	want[0] = totalWeight * float64(vals[0])

	assertVec(t, "trace", DecodeCoeffs(params.RLWE, dec.DecryptNew(traced), params.Delta), want)
}

// registerAll registers every party and, by decrypting each ct_R, recovers
// the randomness it sampled so the plain-Go reference model can predict the
// same outcome.
func registerAll(t *testing.T, enc *rgsw.Encryptor, dec *rlwe.Decryptor, eval *rgsw.Evaluator, params CircuitParams, parties []Party) ([]*Registration, []refNode) {
	t.Helper()

	rank, stride := params.RLWE.N(), params.Stride

	regs := make([]*Registration, len(parties))
	leaves := make([]refNode, len(parties))
	for i, p := range parties {
		regs[i] = Register(enc, params, p)

		idx, val := findNonzero(t, decryptRGSW(enc, dec, eval, params, regs[i].CtR))
		if math.Abs(val-1) > 1e-6 || idx%stride != 0 {
			t.Fatalf("party %d: unexpected ctR encoding at %d = %v", i, idx, val)
		}
		leaves[i] = refNode{w: p.Weight, r: uint64(idx / stride), h: refHVec(rank, stride, p)}
	}
	return regs, leaves
}

// refNode mirrors a [Registration] as plain (unencrypted) data: weight,
// (unreduced) randomness, and the coefficient vector ct_H decrypts to.
type refNode struct {
	w uint64
	r uint64
	h []float64
}

// refHVec builds the plain ct_H coefficient vector for one [Party]: its
// commitment at every stride-th slot below its weight.
func refHVec(rank, stride int, p Party) []float64 {
	h := make([]float64, rank)
	for k := uint64(0); k < p.Weight; k++ {
		h[stride*int(k)] = float64(p.Commitment)
	}
	return h
}

// refCombineEcd mirrors [Aggregate]'s first pass on plain data: shift the
// accumulator by next's weight in the negacyclic ring, then add next's own
// commitment vector unshifted.
func refCombineEcd(rank, stride int, acc, next refNode) refNode {
	h := shiftNegacyclic(acc.h, int(next.w)*stride, rank)
	for i, v := range next.h {
		h[i] += v
	}
	return refNode{w: acc.w + next.w, r: acc.r + next.r, h: h}
}

// refAggregate mirrors [Aggregate] on plain data, matching its two-pass
// structure exactly.
func refAggregate(rank, stride int, nodes []refNode) refNode {
	acc := refNode{h: make([]float64, rank)}
	for _, n := range nodes {
		acc = refCombineEcd(rank, stride, acc, n)
	}
	for _, n := range nodes {
		acc.h = shiftNegacyclic(acc.h, int(n.r)*stride, rank)
	}
	return acc
}

// shiftNegacyclic shifts h by shift positions in Z[X]/(X^rank+1): index i
// moves to (i+shift) mod 2*rank, with a sign flip whenever that wraps past
// rank (X^rank = -1).
func shiftNegacyclic(h []float64, shift, rank int) []float64 {
	out := make([]float64, rank)
	period := 2 * rank
	shift = ((shift % period) + period) % period
	for i, v := range h {
		if v == 0 {
			continue
		}
		idx := i + shift
		if idx >= period {
			idx -= period
		}
		if idx < rank {
			out[idx] += v
		} else {
			out[idx-rank] -= v
		}
	}
	return out
}

// decryptRGSW recovers the monomial an [rgsw.Ciphertext] encrypts by applying
// it to a fresh encryption of 1 -- an RGSW ciphertext cannot be decrypted
// directly, only applied to an RLWE one.
func decryptRGSW(enc *rgsw.Encryptor, dec *rlwe.Decryptor, eval *rgsw.Evaluator, params CircuitParams, gsw *rgsw.Ciphertext) []float64 {
	one := make([]uint64, params.RLWE.N())
	one[0] = 1

	ct, err := enc.EncryptNew(EncodeCoeffs(params.RLWE, one, params.Delta))
	if err != nil {
		panic(err)
	}

	eval.ExternalProduct(ct, gsw, ct)

	return DecodeCoeffs(params.RLWE, dec.DecryptNew(ct), params.Delta)
}

// findNonzero locates the single coefficient that rounds to nonzero, and
// reports the absolute precision (raw value vs. its rounding) over every
// coefficient, so the noise magnitude stays visible even when the rounded
// values are right.
func findNonzero(t *testing.T, coeffs []float64) (int, float64) {
	t.Helper()

	idx, val, maxErr := -1, 0.0, 0.0
	for i, v := range coeffs {
		rounded := math.Round(v)
		maxErr = max(maxErr, math.Abs(v-rounded))
		if rounded != 0 {
			if idx != -1 {
				t.Fatalf("multiple nonzero coeffs at %d and %d", idx, i)
			}
			idx, val = i, rounded
		}
	}
	if idx == -1 {
		t.Fatal("no nonzero coeff found")
	}
	t.Logf("precision = %.1f bits", -math.Log2(maxErr))
	return idx, val
}

func assertOneHot(t *testing.T, name string, coeffs []float64, want int, value float64) {
	t.Helper()
	wantVec := make([]float64, len(coeffs))
	wantVec[want] = value
	assertVec(t, name, coeffs, wantVec)
}

// assertVec checks raw decoded coefficients against the exact expected
// integers by rounding, but reports the absolute precision (|got-want| before
// rounding) so the noise magnitude is visible in passing and failing runs
// alike.
func assertVec(t *testing.T, name string, got, want []float64) {
	t.Helper()

	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch: got %d, want %d", name, len(got), len(want))
	}

	maxErr := 0.0
	for i := range got {
		absErr := math.Abs(got[i] - want[i])
		maxErr = max(maxErr, absErr)
		if math.Round(got[i]) != want[i] {
			t.Errorf("%s: coeff[%d] = %v, want %v (precision %.1f bits)", name, i, got[i], want[i], -math.Log2(absErr))
		}
	}
	t.Logf("%s: precision = %.1f bits", name, -math.Log2(maxErr))
}
