package wsslergsw

import (
	"math/bits"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
)

// ExtractionGaloisElements returns the Galois elements the relative trace
// Tr_{R/Z[Z]}, Z = X^(N/C), applies by repeated doubling ([Trace]).
//
// The trace sums over G_C = {g in (Z/2N)^* : g = 1 mod 2C}, the automorphisms
// fixing Z, a group of order N/C. For C >= 2 it lies in the cyclic group <5>
// and is generated by 5^(C/2), so the doubling steps are 5^(2^t) for
// log2(C)-1 <= t < log2(N)-1: every subset product is a distinct element of
// G_C. For C = 1 it is all of (Z/2N)^*, <5> times the conjugation 2N-1.
// Either way there are log2(N/C) elements.
func ExtractionGaloisElements(params CircuitParams) []uint64 {
	N := params.RLWE.N()
	C := params.Fragments
	twoN := uint64(2 * N)

	first := 0
	if C > 1 {
		first = bits.Len(uint(C)) - 2 // log2(C) - 1
	}

	g := uint64(5)
	for t := 0; t < first; t++ {
		g = g * g % twoN
	}
	elems := make([]uint64, 0)
	for t := first; t < bits.Len(uint(N))-2; t++ { // t < log2(N) - 1
		elems = append(elems, g)
		g = g * g % twoN
	}
	if C == 1 {
		elems = append(elems, twoN-1)
	}
	return elems
}

// Trace sums ct over the automorphisms generated by elems, by repeated
// doubling: ct <- ct + sigma_g(ct) for each g in turn, so the result is the
// sum over every subset product of elems. With [ExtractionGaloisElements] that
// is the relative trace Tr_{R/Z[Z]}: it keeps the coefficients at multiples of
// N/C, scaled by N/C, and annihilates every other coefficient -- exactly, as a
// map on R, so on the error as well as on the message. The evaluator must hold
// a Galois key for every element (see [SetupKeys]).
func Trace(eval *rlwe.Evaluator, ct *rlwe.Ciphertext, elems []uint64) (*rlwe.Ciphertext, error) {
	params := eval.GetRLWEParameters()
	ringQ := params.RingQ().AtLevel(ct.Level())

	acc := ct.CopyNew()
	tmp := rlwe.NewCiphertext(params, 1, ct.Level())

	for _, g := range elems {
		if err := eval.Automorphism(acc, g, tmp); err != nil {
			return nil, err
		}
		ringQ.Add(acc.Value[0], tmp.Value[0], acc.Value[0])
		ringQ.Add(acc.Value[1], tmp.Value[1], acc.Value[1])
	}

	return acc, nil
}
