package wsslergsw

import (
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
)

// TraceGaloisElements returns the Galois elements [Trace]'s doubling
// algorithm applies, to sum over the full Galois group of the power-of-two
// cyclotomic subring of cyclotomic index cycloIdx.
//
// Gal((Z/cycloIdx Z)^*) has order cycloIdx/2, generated by 5 (of order
// cycloIdx/4) together with the conjugation cycloIdx-1 (of order 2). Summing
// over the whole group takes one automorphism per doubling step: 5^(2^j) for
// j = 0 .. log2(cycloIdx/4)-1, then a final conjugation.
//
// Note this is deliberately not [rlwe.GaloisElementsForTrace]: that one sums
// over the full ring's group (giving a factor N and log2(N) key-switches),
// whereas the message here already lives in the subring generated by
// Y = X^Stride, so only the relative trace over that subring is needed --
// factor W, log2(W) key-switches -- matching Fig. 1's W^-1 normalization.
// The elements are reduced mod cycloIdx = 2W and then used as ordinary
// automorphism indices of the full ring, where they act on Y as Y -> Y^g.
func TraceGaloisElements(cycloIdx int) []uint64 {
	order := cycloIdx / 4 // order of the cyclic subgroup <5> mod cycloIdx

	elems := make([]uint64, 0)
	g := uint64(5 % cycloIdx)
	for k := order; k > 1; k /= 2 {
		elems = append(elems, g)
		g = (g * g) % uint64(cycloIdx)
	}
	return append(elems, uint64(cycloIdx-1))
}

// Trace sums ct over the Galois group of the subring of cyclotomic index
// cycloIdx, i.e. Trace(ct) = sum_{g in Gal} sigma_g(ct), in log2(cycloIdx)
// key-switches via repeated doubling over [TraceGaloisElements]. The
// evaluator must hold a Galois key for every element that function returns
// (see [SetupKeys]); the order of the sequence matters, which is why
// cycloIdx is taken here rather than iterating over the key set.
//
// Applied to a message in the subring, this annihilates every coefficient but
// the constant one and scales that one by W = cycloIdx/2.
func Trace(eval *rlwe.Evaluator, ct *rlwe.Ciphertext, cycloIdx int) (*rlwe.Ciphertext, error) {
	params := eval.GetRLWEParameters()
	ringQ := params.RingQ().AtLevel(ct.Level())

	acc := ct.CopyNew()
	tmp := rlwe.NewCiphertext(params, 1, ct.Level())

	for _, g := range TraceGaloisElements(cycloIdx) {
		if err := eval.Automorphism(acc, g, tmp); err != nil {
			return nil, err
		}
		ringQ.Add(acc.Value[0], tmp.Value[0], acc.Value[0])
		ringQ.Add(acc.Value[1], tmp.Value[1], acc.Value[1])
	}

	return acc, nil
}
